// Generated by gencpp from file team2_package/globalwaypoints.msg
// DO NOT EDIT!


#ifndef TEAM2_PACKAGE_MESSAGE_GLOBALWAYPOINTS_H
#define TEAM2_PACKAGE_MESSAGE_GLOBALWAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace team2_package
{
template <class ContainerAllocator>
struct globalwaypoints_
{
  typedef globalwaypoints_<ContainerAllocator> Type;

  globalwaypoints_()
    : header()
    , road_options()
    , x()
    , y()  {
    }
  globalwaypoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , road_options(_alloc)
    , x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _road_options_type;
  _road_options_type road_options;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _x_type;
  _x_type x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_type;
  _y_type y;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(VOID)
  #undef VOID
#endif
#if defined(_WIN32) && defined(LEFT)
  #undef LEFT
#endif
#if defined(_WIN32) && defined(RIGHT)
  #undef RIGHT
#endif
#if defined(_WIN32) && defined(STRAIGHT)
  #undef STRAIGHT
#endif
#if defined(_WIN32) && defined(LANEFOLLOW)
  #undef LANEFOLLOW
#endif
#if defined(_WIN32) && defined(CHANGELANELEFT)
  #undef CHANGELANELEFT
#endif
#if defined(_WIN32) && defined(CHANGELANERIGHT)
  #undef CHANGELANERIGHT
#endif

  enum {
    VOID = -1,
    LEFT = 1,
    RIGHT = 2,
    STRAIGHT = 3,
    LANEFOLLOW = 4,
    CHANGELANELEFT = 5,
    CHANGELANERIGHT = 6,
  };


  typedef boost::shared_ptr< ::team2_package::globalwaypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team2_package::globalwaypoints_<ContainerAllocator> const> ConstPtr;

}; // struct globalwaypoints_

typedef ::team2_package::globalwaypoints_<std::allocator<void> > globalwaypoints;

typedef boost::shared_ptr< ::team2_package::globalwaypoints > globalwaypointsPtr;
typedef boost::shared_ptr< ::team2_package::globalwaypoints const> globalwaypointsConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team2_package::globalwaypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team2_package::globalwaypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::team2_package::globalwaypoints_<ContainerAllocator1> & lhs, const ::team2_package::globalwaypoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.road_options == rhs.road_options &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::team2_package::globalwaypoints_<ContainerAllocator1> & lhs, const ::team2_package::globalwaypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace team2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::team2_package::globalwaypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team2_package::globalwaypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::globalwaypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::globalwaypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::globalwaypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::globalwaypoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team2_package::globalwaypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f169d64c8dec16596456b30665e5fbde";
  }

  static const char* value(const ::team2_package::globalwaypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf169d64c8dec1659ULL;
  static const uint64_t static_value2 = 0x6456b30665e5fbdeULL;
};

template<class ContainerAllocator>
struct DataType< ::team2_package::globalwaypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team2_package/globalwaypoints";
  }

  static const char* value(const ::team2_package::globalwaypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team2_package::globalwaypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"int8[] road_options\n"
"float64[] x\n"
"float64[] y\n"
"\n"
"int8 VOID=-1\n"
"int8 LEFT=1\n"
"int8 RIGHT=2\n"
"int8 STRAIGHT=3\n"
"int8 LANEFOLLOW=4\n"
"int8 CHANGELANELEFT=5\n"
"int8 CHANGELANERIGHT=6\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::team2_package::globalwaypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team2_package::globalwaypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.road_options);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct globalwaypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team2_package::globalwaypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team2_package::globalwaypoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "road_options[]" << std::endl;
    for (size_t i = 0; i < v.road_options.size(); ++i)
    {
      s << indent << "  road_options[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.road_options[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM2_PACKAGE_MESSAGE_GLOBALWAYPOINTS_H
