// Generated by gencpp from file team2_package/longitudinal_controller.msg
// DO NOT EDIT!


#ifndef TEAM2_PACKAGE_MESSAGE_LONGITUDINAL_CONTROLLER_H
#define TEAM2_PACKAGE_MESSAGE_LONGITUDINAL_CONTROLLER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace team2_package
{
template <class ContainerAllocator>
struct longitudinal_controller_
{
  typedef longitudinal_controller_<ContainerAllocator> Type;

  longitudinal_controller_()
    : throttle(0.0)
    , brake(0.0)  {
    }
  longitudinal_controller_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , brake(0.0)  {
  (void)_alloc;
    }



   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _brake_type;
  _brake_type brake;





  typedef boost::shared_ptr< ::team2_package::longitudinal_controller_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team2_package::longitudinal_controller_<ContainerAllocator> const> ConstPtr;

}; // struct longitudinal_controller_

typedef ::team2_package::longitudinal_controller_<std::allocator<void> > longitudinal_controller;

typedef boost::shared_ptr< ::team2_package::longitudinal_controller > longitudinal_controllerPtr;
typedef boost::shared_ptr< ::team2_package::longitudinal_controller const> longitudinal_controllerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team2_package::longitudinal_controller_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team2_package::longitudinal_controller_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::team2_package::longitudinal_controller_<ContainerAllocator1> & lhs, const ::team2_package::longitudinal_controller_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle &&
    lhs.brake == rhs.brake;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::team2_package::longitudinal_controller_<ContainerAllocator1> & lhs, const ::team2_package::longitudinal_controller_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace team2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::team2_package::longitudinal_controller_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team2_package::longitudinal_controller_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::longitudinal_controller_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::longitudinal_controller_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::longitudinal_controller_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::longitudinal_controller_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team2_package::longitudinal_controller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1220857b9c02b48ec2fc3654fbd7e1a3";
  }

  static const char* value(const ::team2_package::longitudinal_controller_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1220857b9c02b48eULL;
  static const uint64_t static_value2 = 0xc2fc3654fbd7e1a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::team2_package::longitudinal_controller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team2_package/longitudinal_controller";
  }

  static const char* value(const ::team2_package::longitudinal_controller_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team2_package::longitudinal_controller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 throttle\n"
"float32 brake\n"
;
  }

  static const char* value(const ::team2_package::longitudinal_controller_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team2_package::longitudinal_controller_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct longitudinal_controller_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team2_package::longitudinal_controller_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team2_package::longitudinal_controller_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "brake: ";
    Printer<float>::stream(s, indent + "  ", v.brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM2_PACKAGE_MESSAGE_LONGITUDINAL_CONTROLLER_H
