// Generated by gencpp from file team2_package/tracked_object_array.msg
// DO NOT EDIT!


#ifndef TEAM2_PACKAGE_MESSAGE_TRACKED_OBJECT_ARRAY_H
#define TEAM2_PACKAGE_MESSAGE_TRACKED_OBJECT_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <team2_package/tracked_object.h>

namespace team2_package
{
template <class ContainerAllocator>
struct tracked_object_array_
{
  typedef tracked_object_array_<ContainerAllocator> Type;

  tracked_object_array_()
    : header()
    , objects()  {
    }
  tracked_object_array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::team2_package::tracked_object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::team2_package::tracked_object_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::team2_package::tracked_object_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team2_package::tracked_object_array_<ContainerAllocator> const> ConstPtr;

}; // struct tracked_object_array_

typedef ::team2_package::tracked_object_array_<std::allocator<void> > tracked_object_array;

typedef boost::shared_ptr< ::team2_package::tracked_object_array > tracked_object_arrayPtr;
typedef boost::shared_ptr< ::team2_package::tracked_object_array const> tracked_object_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team2_package::tracked_object_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team2_package::tracked_object_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::team2_package::tracked_object_array_<ContainerAllocator1> & lhs, const ::team2_package::tracked_object_array_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::team2_package::tracked_object_array_<ContainerAllocator1> & lhs, const ::team2_package::tracked_object_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace team2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::team2_package::tracked_object_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team2_package::tracked_object_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::tracked_object_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::tracked_object_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::tracked_object_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::tracked_object_array_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team2_package::tracked_object_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c50235ee5e169f41fa0e37ba85beeba3";
  }

  static const char* value(const ::team2_package::tracked_object_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc50235ee5e169f41ULL;
  static const uint64_t static_value2 = 0xfa0e37ba85beeba3ULL;
};

template<class ContainerAllocator>
struct DataType< ::team2_package::tracked_object_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team2_package/tracked_object_array";
  }

  static const char* value(const ::team2_package::tracked_object_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team2_package::tracked_object_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"tracked_object[] objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: team2_package/tracked_object\n"
"float64 center_x\n"
"float64 center_y\n"
"float64 v_x\n"
"float64 v_y\n"
"float64 size_x\n"
"float64 size_y\n"
;
  }

  static const char* value(const ::team2_package::tracked_object_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team2_package::tracked_object_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tracked_object_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team2_package::tracked_object_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team2_package::tracked_object_array_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::team2_package::tracked_object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM2_PACKAGE_MESSAGE_TRACKED_OBJECT_ARRAY_H
