// Generated by gencpp from file team2_package/vehicle_state.msg
// DO NOT EDIT!


#ifndef TEAM2_PACKAGE_MESSAGE_VEHICLE_STATE_H
#define TEAM2_PACKAGE_MESSAGE_VEHICLE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace team2_package
{
template <class ContainerAllocator>
struct vehicle_state_
{
  typedef vehicle_state_<ContainerAllocator> Type;

  vehicle_state_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  vehicle_state_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::team2_package::vehicle_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::team2_package::vehicle_state_<ContainerAllocator> const> ConstPtr;

}; // struct vehicle_state_

typedef ::team2_package::vehicle_state_<std::allocator<void> > vehicle_state;

typedef boost::shared_ptr< ::team2_package::vehicle_state > vehicle_statePtr;
typedef boost::shared_ptr< ::team2_package::vehicle_state const> vehicle_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::team2_package::vehicle_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::team2_package::vehicle_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::team2_package::vehicle_state_<ContainerAllocator1> & lhs, const ::team2_package::vehicle_state_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::team2_package::vehicle_state_<ContainerAllocator1> & lhs, const ::team2_package::vehicle_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace team2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::team2_package::vehicle_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::team2_package::vehicle_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::vehicle_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::team2_package::vehicle_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::vehicle_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::team2_package::vehicle_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::team2_package::vehicle_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47802147045815b06859cca542c21d31";
  }

  static const char* value(const ::team2_package::vehicle_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47802147045815b0ULL;
  static const uint64_t static_value2 = 0x6859cca542c21d31ULL;
};

template<class ContainerAllocator>
struct DataType< ::team2_package::vehicle_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "team2_package/vehicle_state";
  }

  static const char* value(const ::team2_package::vehicle_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::team2_package::vehicle_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::team2_package::vehicle_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::team2_package::vehicle_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicle_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::team2_package::vehicle_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::team2_package::vehicle_state_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEAM2_PACKAGE_MESSAGE_VEHICLE_STATE_H
